# Example config for `python -m analysis convert`

convert:
  book: PSA
  input_csv: ../../../out/psa_145_zero_shot.csv
  output_json: ../../../out/psa_145_zero_shot.json
  translation_language: en
  translation_title: ulb
  usfm_root: ../../../lang
